### ISSUE TITLE
need a detailed description how to use sources

### ISSUE THREAD

**Issue by Gargo** [vueschool/learn-vuex#2]
Usually they make a separate folder for each lesson but what to do with this repo?

**Comment by hootlex** [comment]
You can download the repo and have the final source code.
Each lesson's code is an individual commit https://github.com/vueschool/learn-vuex/commits/master

If you want to check the code for a specific lesson, checkout the corresponding commit locally. This is very easy if you use a GUI with git, for ex. source tree.

![](https://i.imgur.com/KKarPED.png)
